Repository vingkan/nflbigdatabowl2023, pull requests merged in 2022-12, with the labels that each got.

#2 Install pre-commit hooks in requirements.
  requirements-dev.txt
  run.sh
Labels: devtools

#3 Move Kaggle download and pre-commit to background tasks.
  .gitpod.yml
  requirements-dev.txt
  run.sh
Labels: devtools

#4 Add first draft of pipeline to calculate pocket area.
  notebooks/vinesh/pipeline_example.ipynb
  requirements.txt
  src/metrics/pocket_area/all.py
  src/metrics/pocket_area/base.py
  src/pipeline/flows/__init__.py
  src/pipeline/flows/main.py
  src/pipeline/tasks/__init__.py
  src/pipeline/tasks/dataframes.py
  src/pipeline/tasks/dataframes_test.py
  src/pipeline/tasks/frames.py
  src/pipeline/tasks/frames_test.py
  src/pipeline/tasks/pocket_area.py
  src/pipeline/tasks/pocket_area_test.py
Labels: enhancement

#5 Return pocket metadata in addition to area.
  notebooks/vinesh/example.ipynb
  notebooks/vinesh/pipeline_example.ipynb
  src/metrics/pocket_area/all.py
  src/metrics/pocket_area/base.py
  src/metrics/pocket_area/passer_radius_area.py
  src/metrics/pocket_area/passer_radius_area_test.py
  src/pipeline/tasks/pocket_area.py
  src/pipeline/tasks/pocket_area_test.py
Labels: enhancement, refactor

#7 pass area based on corvex hull of pass blockers/passers
  notebooks/vinesh/pipeline_example.ipynb
  src/metrics/pocket_area/all.py
  src/metrics/pocket_area/helpers.py
  src/metrics/pocket_area/pocket_pb_ch_area.py
  src/metrics/pocket_area/pocket_pb_ch_area_test.py
Labels: enhancement

#6 Add functions to visualize pocket area.
  .gitpod.yml
  README.md
  notebooks/vinesh/visualization_example.ipynb
  requirements.txt
  run.sh
  src/pipeline/flows/main.py
  src/pipeline/tasks/__init__.py
  src/pipeline/tasks/constants.py
  src/pipeline/tasks/frames.py
  src/pipeline/tasks/tracking.py
  src/pipeline/tasks/tracking_test.py
  src/visualization/interactive.py
Labels: enhancement, visualization

#8 Integrate pocket area into interactive play visualization.
  .bash_aliases
  .bash_helpers
  .gitpod.yml
  notebooks/vinesh/visualization_example.ipynb
  requirements.txt
  src/metrics/pocket_area/base.py
  src/metrics/pocket_area/passer_radius_area.py
  src/metrics/pocket_area/passer_radius_area_test.py
  src/pipeline/flows/main.py
  src/pipeline/tasks/frames.py
  src/pipeline/tasks/frames_test.py
  src/pipeline/tasks/pocket_area.py
  src/pipeline/tasks/pocket_area_test.py
  src/visualization/interactive.py
  src/visualization/pocket_area.py
  src/visualization/pocket_area_test.py
Labels: enhancement, visualization

#9 Add pocket area timeline chart and play selector.
  notebooks/vinesh/visualization_example.ipynb
  src/pipeline/tasks/tracking.py
  src/visualization/interactive_play_selector.py
  src/visualization/interactive_pocket_area.py
Labels: enhancement, refactor, visualization

#10 Move all GitPod startup tasks to command instead of init.
  .gitpod.yml
Labels: devtools

#11 Updates to interactive play selector.
  notebooks/vinesh/visualization_example.ipynb
  src/pipeline/flows/main.py
  src/pipeline/tasks/dataframes.py
  src/pipeline/tasks/dataframes_test.py
  src/visualization/interactive_play_selector.py
  src/visualization/interactive_pocket_area.py
Labels: enhancement, visualization

#12 Clean event data per frame.
  notebooks/vinesh/clean_event.ipynb
  src/pipeline/flows/main.py
  src/pipeline/tasks/__init__.py
  src/pipeline/tasks/events.py
  src/pipeline/tasks/events_test.py
Labels: enhancement

#13 Reorient tracking data to face the same way.
  notebooks/vinesh/reorient_tracking_data.ipynb
  notebooks/vinesh/visualization_example.ipynb
  src/pipeline/flows/main.py
  src/pipeline/tasks/tracking.py
  src/pipeline/tasks/tracking_test.py
Labels: enhancement, refactor
