Repository vingkan/nflbigdatabowl2023, pull requests merged in 2023-01, with the labels that each got.

#14 Add pocket eligibility to pipeline.
  notebooks/vinesh/visualization_example.ipynb
  src/pipeline/flows/main.py
  src/pipeline/tasks/__init__.py
  src/pipeline/tasks/eligibility.py
  src/pipeline/tasks/eligibility_test.py
  src/pipeline/tasks/events.py
  src/pipeline/tasks/tracking.py
  src/visualization/interactive_pocket_area.py
  src/visualization/pocket_area.py
Labels: enhancement, refactor, visualization

#16 Pocket average (metrics complete)
  notebooks/tabor/Pocket Area Metrics.ipynb
Labels: prototype

#17 Integrate play metrics data into pipeline.
  notebooks/vinesh/play_metrics_example.ipynb
  notebooks/vinesh/run_pipeline.ipynb
  src/pipeline/flows/main.py
  src/pipeline/tasks/__init__.py
  src/pipeline/tasks/eligibility.py
  src/pipeline/tasks/play_metrics.py
  src/pipeline/tasks/play_metrics_test.py
  src/pipeline/tasks/play_windows.py
  src/pipeline/tasks/play_windows_test.py
  src/pipeline/tasks/test_helpers.py
  src/pipeline/tasks/test_helpers_test.py
Labels: enhancement, refactor

#18 Improve performance of tracking data reorientation.
  notebooks/vinesh/run_pipeline.ipynb
  src/pipeline/tasks/tracking.py
Labels: refactor

#19 Improve performance of frame record aggregation.
  notebooks/vinesh/run_pipeline.ipynb
  src/pipeline/tasks/dataframes.py
  src/pipeline/tasks/frames.py
Labels: refactor

#20 Add pocket area function based on Voronoi diagram
  notebooks/alek/rushers_pocket_area.ipynb
  notebooks/alek/voronoi_pocket_area.ipynb
  notebooks/vinesh/visualization_example.ipynb
  requirements.txt
  src/metrics/pocket_area/all.py
  src/metrics/pocket_area/voronoi_pocket_area.py
  src/metrics/pocket_area/voronoi_pocket_area_test.py
  src/pipeline/tasks/constants.py
  src/pipeline/tasks/pocket_area.py
  src/pipeline/tasks/pocket_area_test.py
  src/pipeline/tasks/tracking.py
  src/visualization/pocket_area.py
Labels: enhancement, refactor

#21 Read multiple weeks of tracking data.
  notebooks/vinesh/area_aggregation.ipynb
  notebooks/vinesh/run_pipeline.ipynb
  notebooks/vinesh/visualization_example.ipynb
  src/pipeline/flows/main.py
  src/pipeline/tasks/dataframes.py
  src/pipeline/tasks/tracking.py
  src/visualization/interactive_play_selector.py
Labels: enhancement, refactor, visualization

#22 Fix play metrics join to avoid suffixed column names.
  notebooks/vinesh/area_aggregation.ipynb
  notebooks/vinesh/visualization_example.ipynb
  src/pipeline/tasks/play_metrics.py
Labels: bug

#24 Fix logic for finding pocket end frame.
  notebooks/vinesh/clean_event.ipynb
  notebooks/vinesh/visualization_example.ipynb
  src/pipeline/flows/main.py
  src/pipeline/tasks/eligibility.py
  src/pipeline/tasks/eligibility_test.py
  src/pipeline/tasks/events.py
  src/pipeline/tasks/tracking.py
  src/visualization/interactive_pocket_area.py
Labels: enhancement, refactor, visualization

#25 Add before end time window.
  notebooks/vinesh/area_aggregation.ipynb
  notebooks/vinesh/visualization_example.ipynb
  src/pipeline/tasks/play_metrics.py
  src/pipeline/tasks/play_windows.py
  src/pipeline/tasks/play_windows_test.py
Labels: enhancement

#26 Add median and average area to play metrics and create aggregated analytics.
  notebooks/vinesh/area_aggregation.ipynb
  notebooks/vinesh/run_pipeline.ipynb
  notebooks/vinesh/visualization_example.ipynb
  requirements.txt
  src/pipeline/flows/main.py
  src/pipeline/tasks/play_metrics.py
  src/pipeline/tasks/play_metrics_test.py
  src/pipeline/tasks/play_windows.py
Labels: bug, enhancement, refactor, visualization, prototype

#28 Configure package for PyPi.
  CHANGELOG.md
  MANIFEST.in
  README.md
  pyproject.toml
  requirements-dev.txt
Labels: enhancement, devtools

#29 Add visualizers for area scatter plots.
  notebooks/vinesh/area_aggregation.ipynb
  notebooks/vinesh/run_pipeline.ipynb
  requirements.txt
  src/visualization/formations.py
  src/visualization/helpers.py
  src/visualization/logos.py
  src/visualization/scatter.py
Labels: enhancement, refactor, visualization

#30 Fix requests for team logos.
  CHANGELOG.md
  notebooks/vinesh/area_aggregation.ipynb
  notebooks/vinesh/run_pipeline.ipynb
  pyproject.toml
  src/visualization/logos.py
Labels: bug, visualization

#31 Configure pipeline from keyword arguments.
  notebooks/vinesh/visualization_example.ipynb
  src/pipeline/flows/main.py
Labels: enhancement, refactor

#32 Hide calculate pocket area error messages.
  src/pipeline/tasks/pocket_area.py
Labels: devtools

#33 Copy series before swapping coordinates.
  src/pipeline/tasks/tracking.py
Labels: bug

#34 Refactor codebase for compatibility with Python 3.7.12 on Kaggle.
  CHANGELOG.md
  notebooks/vinesh/run_pipeline.ipynb
  pyproject.toml
  requirements.txt
  src/metrics/pocket_area/helpers.py
  src/metrics/pocket_area/helpers_test.py
  src/pipeline/flows/main.py
  src/pipeline/tasks/eligibility.py
  src/pipeline/tasks/pocket_area.py
  src/pipeline/tasks/pocket_area_test.py
  src/visualization/interactive_pocket_area.py
  src/visualization/pocket_area.py
Labels: refactor

#35 Download processed data from Kaggle.
  notebooks/vinesh/area_aggregation.ipynb
  notebooks/vinesh/visualization_example.ipynb
  run.sh
  src/pipeline/flows/run.py
Labels: enhancement, devtools

#36 Start prototyping spotlight search.
  notebooks/vinesh/spotlight_search.ipynb
  src/pipeline/tasks/__init__.py
  src/pipeline/tasks/spotlight.py
  src/visualization/interactive_pocket_area.py
Labels: enhancement, refactor, visualization, prototype

#37 fixed missing radius visualization
  notebooks/tabor/Pocket_Area_Metric_Application.ipynb
  src/metrics/pocket_area/adaptive_pocket_area.py
Labels: bug, visualization

#39 Center tracking data.
  notebooks/vinesh/heatmap_example.ipynb
  notebooks/vinesh/visualization_example.ipynb
  src/pipeline/flows/main.py
  src/pipeline/tasks/tracking.py
Labels: enhancement, visualization

#40 Quick fix for Voronoi area centering.
  src/metrics/pocket_area/voronoi_pocket_area.py
  src/metrics/pocket_area/voronoi_rushers_only.py
  src/metrics/pocket_area/voronoi_rushers_only_test.py
Labels: bug

#42 Crop convex hull past line of scrimmage.
  notebooks/vinesh/heatmap_example.ipynb
  notebooks/vinesh/run_pipeline.ipynb
  notebooks/vinesh/visualization_example.ipynb
  src/metrics/pocket_area/adaptive_pocket_area_test.py
  src/metrics/pocket_area/all.py
  src/metrics/pocket_area/helpers.py
  src/metrics/pocket_area/pocket_pb_ch_area.py
  src/metrics/pocket_area/pocket_pb_ch_area_test.py
  src/pipeline/tasks/events.py
  src/pipeline/tasks/events_test.py
  src/pipeline/tasks/tracking.py
Labels: bug, refactor, visualization

#43 Create figures.
  notebooks/vinesh/generate_figures.ipynb
  notebooks/vinesh/visualization_example.ipynb
  run.sh
  src/metrics/pocket_area/adaptive_pocket_area.py
  src/visualization/formations.py
  src/visualization/heatmaps.py
  src/visualization/interactive_pocket_area.py
  src/visualization/scatter.py
Labels: enhancement, refactor, visualization

#44 More figures.
  notebooks/vinesh/generate_figures.ipynb
  src/metrics/pocket_area/adaptive_pocket_area.py
  src/visualization/heatmaps.py
  src/visualization/scatter.py
Labels: enhancement, refactor, visualization

#45 Add more windows.
  notebooks/vinesh/generate_figures.ipynb
  src/pipeline/tasks/play_windows.py
  src/pipeline/tasks/play_windows_test.py
  src/visualization/formations.py
  src/visualization/scatter.py
Labels: enhancement, refactor, visualization

#46 Upload figures.
  assets/figure_01.png
  assets/figure_02.png
  assets/figure_03.png
  assets/figure_04.png
  assets/figure_05.png
  assets/figure_06.png
  assets/figure_07.png
  assets/figure_08.png
  assets/figure_09.png
  notebooks/vinesh/generate_figures.ipynb
  src/visualization/heatmaps.py
  src/visualization/scatter.py
Labels: documentation, enhancement, visualization

#47 Fix image width ratio.
  assets/figure_01.png
  assets/figure_02.png
  notebooks/vinesh/generate_figures.ipynb
  src/visualization/interactive_pocket_area.py
Labels: bug, visualization
